---
- hosts: all
  tasks:
  - name: "Install prerequisites."
    yum:
      name:
        - glibc.i686
        - libstdc++.i686
        - wget
      state: latest
  - name: "Add default user game_admin"
    shell: adduser game_admin
  - name: "Making directory"
    shell: mkdir -p /home/game_admin/server/logs /home/game_admin/steam_install
  - name: "Download SteamCMD"
    get_url:
      url: https://steamcdn-a.akamaihd.net/client/installer/steamcmd_linux.tar.gz
      dest: /home/game_admin/steam_install/steamcmd_linux.tar.gz
      mode: '0750'
      owner: game_admin
  - name: "Unarchive SteamCMD"
    unarchive:
      src: /home/game_admin/steam_install/steamcmd_linux.tar.gz
      dest: /home/game_admin/steam_install/
      remote_src: yes
  - name: "Remove steamcmd tar extraction no longer needed"
    file:
      path: /home/game_admin/steam_install/steamcmd_linux.tar.gz
      state: absent
  - name: "Make sure everything is game_admin"
    file:
      path: /home/game_admin
      owner: game_admin
      group: game_admin
      mode: '0755'
  - name: "Run Steam CMD for installation as game_admin"
    shell: runuser -l game_admin -c '/home/game_admin/steam_install/./steamcmd.sh +login anonymous +force_install_dir /home/game_admin/server/ +app_update 258550 -validate +quit'
