---
- hosts: all
  tasks:
  - name: "Download Oxide Installer"
    get_url:
      url: https://umod.org/games/rust/download/develop
      dest: /home/game_admin/server/oxide_install.zip
      mode: '0640'
  - name: "Unarchive Oxide Installer"
    unarchive:
      src: /home/game_admin/server/oxide_install.zip
      dest: /home/game_admin/server
      remote_src: yes
  - name: "Change Permission"
    shell: chmod 775 -R /home/game_admin/server/RustDedicated_Data/
  - name: "Change Ownership"
    shell: chown game_admin:game_admin -R /home/game_admin/server/RustDedicated_Data/
