---
- hosts: all
  tasks:
  - name: "Starting up rust server"
    shell: runuser -l game_admin -c 'cd /home/game_admin/server/ && nohup ./RustDedicated -batchmode +server.ip 0.0.0.0 +server.port 28015 +server.tickrate 10 +server.hostname "{{hostname}}" +server.identity "{{identity}}" +server.seed {{seed}} +server.maxplayers {{players}} +server.worldsize {{worldsize}} +server.saveinterval 600 +rcon.ip 0.0.0.0 +rcon.port 28016 +rcon.password "{{rcon_password}}" &> /home/game_admin/server/logs/rustserver-services.log &'