---
- hosts: localhost
  tasks:
  - name: "Setting env: templdpath"
    shell: "export templdpath=$LD_LIBRARY_PATH"
  - name: "Setting env: LD_LIBRARY_PATH"
    shell: "export LD_LIBRARY_PATH={{app_dir}}/valheim/linux64:$LD_LIBRARY_PATH"
  - name: "Setting env: SteamAppId"
    shell: "export SteamAppId=892970"
  - name: "Starting Server Check Log: {{app_dir}}/logs/valheim-services.log"
    shell: "cd {{app_dir}}/valheim/ && nohup ./valheim_server.x86_64 -name \"{{name}}\" -port 2456 -world \"{{world}}\" -password \"{{password}}\" -public {{public}} &> {{app_dir}}/logs/valheim-services.log &"
  - name: "Resetting env: LD_LIBRARY_PATH"
    shell: "export LD_LIBRARY_PATH=$templdpath"