---
- hosts: localhost
  tasks:
  - name: "Setting env: templdpath"
    command: "export templdpath=$LD_LIBRARY_PATH"
  - name: "Setting env: LD_LIBRARY_PATH"
    command: "export LD_LIBRARY_PATH={{app_dir}}/valheim/linux64:$LD_LIBRARY_PATH"
  - name: "Setting env: SteamAppId"
    command: "export SteamAppId=892970"
  - name: "Starting Server Check Log: {{app_dir}}/logs/valheim-services.log"
    command: "nohup cd {{app_dir}}/valheim/ && ./valheim_server.x86_64 -name \"{{name}}\" -port 2456 -world \"{{world}}\" -public {{public}} &> {{app_dir}}/logs/valheim-services.log &"
  - name: "Resetting env: LD_LIBRARY_PATH"
    command: "export LD_LIBRARY_PATH=$templdpath"