---
- hosts: localhost
  tasks:
  - name: "Starting Server Check Log: {{app_dir}}/logs/valheim-services.log"
    shell: cd {{app_dir}}/valheim/ && nohup ./valheim_server.x86_64 -nographics -batchmode -name "{{name}}" -port {{port}} -world "{{world}}" -password "{{password}}" -public {{public}} &> {{app_dir}}/logs/valheim-services.log &
    environment:
      templdpath: "$LD_LIBRARY_PATH"
      LD_LIBRARY_PATH: "{{app_dir}}/valheim/linux64:$LD_LIBRARY_PATH"
      SteamAppId: "892970"