---
- hosts: localhost
  tasks:
  - name: Confirm Valheim is running
    command: pgrep valheim_server
    register: valheim_pid
    ignore_errors: yes
  - name: "Stopping Valheim Server!"
    shell: kill {{valheim_pid.stdout}}
    when: valheim_pid.stdout != ""
