---
- hosts: localhost
  tasks:
  - name: "Install prerequisites."
    yum:
      name:
        - java-1.8.0-openjdk
        - wget
      state: latest
  - name: "Making directory"
    shell: "mkdir -p {{app_dir}}/logs"
  - name: "Create eula.txt"
    copy:
      dest: "{{app_dir}}/eula.txt"
      content: |
        eula=true
  - name: "Create eula.txt"
    copy:
      dest: "{{app_dir}}/server.properties"
      content: |
        server-port=25565
        rcon.port=25575
        query.port=25565
        rcon.password=25575
        enable-rcon=true
        level-name=world
        motd=Minecraft Server
        max-players=20
        level-seed=55
  - name: "Download minecraft"
    get_url:
      url: https://launcher.mojang.com/v1/objects/1b557e7b033b583cd9f66746b7a9ab1ec1673ced/server.jar
      dest: "{{app_dir}}/server.jar"
      mode: '0750'



