---
- hosts: all
  tasks:
  - name: "Install prerequisites."
    yum:
      name:
        - java-1.8.0-openjdk
        - wget
        - python3.x86_64
      state: latest
  - name: "Making directory"
    shell: "mkdir -p {{app_dir}}/server/logs"
  - name: "Create eula.txt"
    copy:
      dest: "{{app_dir}}/server/eula.txt"
      content: |
        eula=true
  - name: "Create eula.txt"
    copy:
      dest: "{{app_dir}}/server/server.properties"
      content: |
        rcon.port={{rcon_password}}
        rcon.password={{rcon_password}}
        enable-rcon=true
  - name: "Download minecraft"
    get_url:
      url: https://launcher.mojang.com/v1/objects/ed76d597a44c5266be2a7fcd77a8270f1f0bc118/server.jar
      dest: "{{app_dir}}/server/server.jar"
      mode: '0750'



