---
- hosts: localhost
  tasks:
  - name: "Install prerequisites."
    yum:
      name:
        - glibc.i686
        - libstdc++.i686
        - wget
        - unzip
      state: latest
  - name: "Creating Logs folder"
    file:
      path: "{{app_dir}}/logs"
      state: directory
      mode: '0755'
  - name: "Creating a directory in {{app_dir}} called terraria"
    file:
      path: "{{app_dir}}/terraria"
      state: directory
      mode: '0755'
  - name: "Download Terraria Server files 1.4.1.2"
    get_url:
      url: https://terraria.org/system/dedicated_servers/archives/000/000/042/original/terraria-server-1412.zip
      dest: "{{app_dir}}/steam_install/terraria-server-1412.zip"
      mode: '0750'
  - name: "Unarchive Zip file"
    unarchive:
      src: "{{app_dir}}/terraria/terraria-server-1412.zip"
      dest: "{{app_dir}}/terraria/"
      remote_src: yes
  - name: "Remove Zip file no longer needed"
    file:
      path: "{{app_dir}}/terraria/terraria-server-1412.zip"
      state: absent
